// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cyber/graph/v1beta1/snapshot.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GraphSnapshot struct {
	Header    *GraphSnapshotHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Particles []*Particle          `protobuf:"bytes,2,rep,name=particles,proto3" json:"particles,omitempty"`
	Links     []*Cyberlink         `protobuf:"bytes,3,rep,name=links,proto3" json:"links,omitempty"`
	Neurons   []*Neuron            `protobuf:"bytes,4,rep,name=neurons,proto3" json:"neurons,omitempty"`
}

func (m *GraphSnapshot) Reset()         { *m = GraphSnapshot{} }
func (m *GraphSnapshot) String() string { return proto.CompactTextString(m) }
func (*GraphSnapshot) ProtoMessage()    {}
func (*GraphSnapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_71bcf52033ef75b2, []int{0}
}
func (m *GraphSnapshot) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GraphSnapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GraphSnapshot.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GraphSnapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphSnapshot.Merge(m, src)
}
func (m *GraphSnapshot) XXX_Size() int {
	return m.Size()
}
func (m *GraphSnapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphSnapshot.DiscardUnknown(m)
}

var xxx_messageInfo_GraphSnapshot proto.InternalMessageInfo

func (m *GraphSnapshot) GetHeader() *GraphSnapshotHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GraphSnapshot) GetParticles() []*Particle {
	if m != nil {
		return m.Particles
	}
	return nil
}

func (m *GraphSnapshot) GetLinks() []*Cyberlink {
	if m != nil {
		return m.Links
	}
	return nil
}

func (m *GraphSnapshot) GetNeurons() []*Neuron {
	if m != nil {
		return m.Neurons
	}
	return nil
}

type GraphSnapshotHeader struct {
	ChainId        string `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Height         uint64 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Timestamp      int64  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ParticlesCount uint64 `protobuf:"varint,4,opt,name=particles_count,json=particlesCount,proto3" json:"particles_count,omitempty"`
	LinksCount     uint64 `protobuf:"varint,5,opt,name=links_count,json=linksCount,proto3" json:"links_count,omitempty"`
	NeuronsCount   uint64 `protobuf:"varint,6,opt,name=neurons_count,json=neuronsCount,proto3" json:"neurons_count,omitempty"`
	RankMerkleRoot []byte `protobuf:"bytes,7,opt,name=rank_merkle_root,json=rankMerkleRoot,proto3" json:"rank_merkle_root,omitempty"`
	Checksum       string `protobuf:"bytes,8,opt,name=checksum,proto3" json:"checksum,omitempty"`
}

func (m *GraphSnapshotHeader) Reset()         { *m = GraphSnapshotHeader{} }
func (m *GraphSnapshotHeader) String() string { return proto.CompactTextString(m) }
func (*GraphSnapshotHeader) ProtoMessage()    {}
func (*GraphSnapshotHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_71bcf52033ef75b2, []int{1}
}
func (m *GraphSnapshotHeader) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GraphSnapshotHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GraphSnapshotHeader.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GraphSnapshotHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphSnapshotHeader.Merge(m, src)
}
func (m *GraphSnapshotHeader) XXX_Size() int {
	return m.Size()
}
func (m *GraphSnapshotHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphSnapshotHeader.DiscardUnknown(m)
}

var xxx_messageInfo_GraphSnapshotHeader proto.InternalMessageInfo

func (m *GraphSnapshotHeader) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *GraphSnapshotHeader) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *GraphSnapshotHeader) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *GraphSnapshotHeader) GetParticlesCount() uint64 {
	if m != nil {
		return m.ParticlesCount
	}
	return 0
}

func (m *GraphSnapshotHeader) GetLinksCount() uint64 {
	if m != nil {
		return m.LinksCount
	}
	return 0
}

func (m *GraphSnapshotHeader) GetNeuronsCount() uint64 {
	if m != nil {
		return m.NeuronsCount
	}
	return 0
}

func (m *GraphSnapshotHeader) GetRankMerkleRoot() []byte {
	if m != nil {
		return m.RankMerkleRoot
	}
	return nil
}

func (m *GraphSnapshotHeader) GetChecksum() string {
	if m != nil {
		return m.Checksum
	}
	return ""
}

type Particle struct {
	Number uint64 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Cid    string `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Rank   uint64 `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`
}

func (m *Particle) Reset()         { *m = Particle{} }
func (m *Particle) String() string { return proto.CompactTextString(m) }
func (*Particle) ProtoMessage()    {}
func (*Particle) Descriptor() ([]byte, []int) {
	return fileDescriptor_71bcf52033ef75b2, []int{2}
}
func (m *Particle) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Particle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Particle.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Particle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Particle.Merge(m, src)
}
func (m *Particle) XXX_Size() int {
	return m.Size()
}
func (m *Particle) XXX_DiscardUnknown() {
	xxx_messageInfo_Particle.DiscardUnknown(m)
}

var xxx_messageInfo_Particle proto.InternalMessageInfo

func (m *Particle) GetNumber() uint64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Particle) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

func (m *Particle) GetRank() uint64 {
	if m != nil {
		return m.Rank
	}
	return 0
}

type Cyberlink struct {
	From    uint64 `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To      uint64 `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	Account uint64 `protobuf:"varint,3,opt,name=account,proto3" json:"account,omitempty"`
	Height  uint64 `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
}

func (m *Cyberlink) Reset()         { *m = Cyberlink{} }
func (m *Cyberlink) String() string { return proto.CompactTextString(m) }
func (*Cyberlink) ProtoMessage()    {}
func (*Cyberlink) Descriptor() ([]byte, []int) {
	return fileDescriptor_71bcf52033ef75b2, []int{3}
}
func (m *Cyberlink) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Cyberlink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Cyberlink.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Cyberlink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cyberlink.Merge(m, src)
}
func (m *Cyberlink) XXX_Size() int {
	return m.Size()
}
func (m *Cyberlink) XXX_DiscardUnknown() {
	xxx_messageInfo_Cyberlink.DiscardUnknown(m)
}

var xxx_messageInfo_Cyberlink proto.InternalMessageInfo

func (m *Cyberlink) GetFrom() uint64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *Cyberlink) GetTo() uint64 {
	if m != nil {
		return m.To
	}
	return 0
}

func (m *Cyberlink) GetAccount() uint64 {
	if m != nil {
		return m.Account
	}
	return 0
}

func (m *Cyberlink) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type Neuron struct {
	Number     uint64 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Address    string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	LinksCount uint64 `protobuf:"varint,3,opt,name=links_count,json=linksCount,proto3" json:"links_count,omitempty"`
	BootStaked uint64 `protobuf:"varint,4,opt,name=boot_staked,json=bootStaked,proto3" json:"boot_staked,omitempty"`
	Hydrogen   uint64 `protobuf:"varint,5,opt,name=hydrogen,proto3" json:"hydrogen,omitempty"`
	Ampere     uint64 `protobuf:"varint,6,opt,name=ampere,proto3" json:"ampere,omitempty"`
	Volt       uint64 `protobuf:"varint,7,opt,name=volt,proto3" json:"volt,omitempty"`
}

func (m *Neuron) Reset()         { *m = Neuron{} }
func (m *Neuron) String() string { return proto.CompactTextString(m) }
func (*Neuron) ProtoMessage()    {}
func (*Neuron) Descriptor() ([]byte, []int) {
	return fileDescriptor_71bcf52033ef75b2, []int{4}
}
func (m *Neuron) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Neuron) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Neuron.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Neuron) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Neuron.Merge(m, src)
}
func (m *Neuron) XXX_Size() int {
	return m.Size()
}
func (m *Neuron) XXX_DiscardUnknown() {
	xxx_messageInfo_Neuron.DiscardUnknown(m)
}

var xxx_messageInfo_Neuron proto.InternalMessageInfo

func (m *Neuron) GetNumber() uint64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Neuron) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Neuron) GetLinksCount() uint64 {
	if m != nil {
		return m.LinksCount
	}
	return 0
}

func (m *Neuron) GetBootStaked() uint64 {
	if m != nil {
		return m.BootStaked
	}
	return 0
}

func (m *Neuron) GetHydrogen() uint64 {
	if m != nil {
		return m.Hydrogen
	}
	return 0
}

func (m *Neuron) GetAmpere() uint64 {
	if m != nil {
		return m.Ampere
	}
	return 0
}

func (m *Neuron) GetVolt() uint64 {
	if m != nil {
		return m.Volt
	}
	return 0
}

func init() {
	proto.RegisterType((*GraphSnapshot)(nil), "cyber.graph.v1beta1.GraphSnapshot")
	proto.RegisterType((*GraphSnapshotHeader)(nil), "cyber.graph.v1beta1.GraphSnapshotHeader")
	proto.RegisterType((*Particle)(nil), "cyber.graph.v1beta1.Particle")
	proto.RegisterType((*Cyberlink)(nil), "cyber.graph.v1beta1.Cyberlink")
	proto.RegisterType((*Neuron)(nil), "cyber.graph.v1beta1.Neuron")
}

func init() {
	proto.RegisterFile("cyber/graph/v1beta1/snapshot.proto", fileDescriptor_71bcf52033ef75b2)
}

var fileDescriptor_71bcf52033ef75b2 = []byte{
	// 557 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x94, 0xbf, 0x6f, 0xd3, 0x40,
	0x14, 0xc7, 0xe3, 0xd8, 0xcd, 0x8f, 0x97, 0x36, 0x54, 0x57, 0x09, 0x99, 0x5f, 0x6e, 0x64, 0x06,
	0xbc, 0x60, 0xab, 0x05, 0x26, 0x16, 0x44, 0x07, 0xda, 0x01, 0x84, 0xae, 0x1b, 0x4b, 0x74, 0xb6,
	0x0f, 0xdb, 0x4a, 0xec, 0xb3, 0xce, 0x97, 0x8a, 0xfc, 0x17, 0xec, 0xfc, 0x3b, 0x0c, 0x8c, 0x1d,
	0x19, 0x51, 0xf2, 0x67, 0xb0, 0xa0, 0x7b, 0xbe, 0xa4, 0x05, 0xd2, 0xed, 0xde, 0x57, 0x9f, 0xef,
	0xf9, 0xbd, 0xef, 0xb3, 0x0d, 0x7e, 0xb2, 0x8c, 0xb9, 0x8c, 0x32, 0xc9, 0xea, 0x3c, 0xba, 0x3a,
	0x89, 0xb9, 0x62, 0x27, 0x51, 0x53, 0xb1, 0xba, 0xc9, 0x85, 0x0a, 0x6b, 0x29, 0x94, 0x20, 0x47,
	0xc8, 0x84, 0xc8, 0x84, 0x86, 0xf1, 0x7f, 0x5b, 0x70, 0xf0, 0x4e, 0x2b, 0x97, 0x06, 0x26, 0x6f,
	0xa0, 0x97, 0x73, 0x96, 0x72, 0xe9, 0x5a, 0x13, 0x2b, 0x18, 0x9d, 0x06, 0xe1, 0x0e, 0x5f, 0xf8,
	0x97, 0xe7, 0x1c, 0x79, 0x6a, 0x7c, 0xe4, 0x35, 0x0c, 0x6b, 0x26, 0x55, 0x91, 0xcc, 0x79, 0xe3,
	0x76, 0x27, 0x76, 0x30, 0x3a, 0x7d, 0xb2, 0xf3, 0x92, 0x8f, 0x86, 0xa2, 0x37, 0x3c, 0x79, 0x09,
	0x7b, 0xf3, 0xa2, 0x9a, 0x35, 0xae, 0x8d, 0x46, 0x6f, 0xa7, 0xf1, 0x4c, 0x6b, 0x1a, 0xa3, 0x2d,
	0x4c, 0x5e, 0x41, 0xbf, 0xe2, 0x0b, 0x29, 0xaa, 0xc6, 0x75, 0xd0, 0xf7, 0x68, 0xa7, 0xef, 0x03,
	0x32, 0x74, 0xc3, 0xfa, 0xdf, 0xba, 0x70, 0xb4, 0x63, 0x12, 0xf2, 0x00, 0x06, 0x49, 0xce, 0x8a,
	0x6a, 0x5a, 0xa4, 0x98, 0xc2, 0x90, 0xf6, 0xb1, 0xbe, 0x48, 0xc9, 0x7d, 0x1d, 0x4f, 0x91, 0xe5,
	0xca, 0xed, 0x4e, 0xac, 0xc0, 0xa1, 0xa6, 0x22, 0x8f, 0x61, 0xa8, 0x8a, 0x92, 0x37, 0x8a, 0x95,
	0xb5, 0x6b, 0x4f, 0xac, 0xc0, 0xa6, 0x37, 0x02, 0x79, 0x06, 0xf7, 0xb6, 0x23, 0x4e, 0x13, 0xb1,
	0xa8, 0x94, 0xeb, 0xa0, 0x7d, 0xbc, 0x95, 0xcf, 0xb4, 0x4a, 0x8e, 0x61, 0x84, 0x13, 0x19, 0x68,
	0x0f, 0x21, 0x40, 0xa9, 0x05, 0x9e, 0xc2, 0x81, 0xe9, 0xde, 0x20, 0x3d, 0x44, 0xf6, 0x8d, 0xd8,
	0x42, 0x01, 0x1c, 0x4a, 0x56, 0xcd, 0xa6, 0x25, 0x97, 0xb3, 0x39, 0x9f, 0x4a, 0x21, 0x94, 0xdb,
	0x9f, 0x58, 0xc1, 0x3e, 0x1d, 0x6b, 0xfd, 0x3d, 0xca, 0x54, 0x08, 0x45, 0x1e, 0xea, 0x49, 0x79,
	0x32, 0x6b, 0x16, 0xa5, 0x3b, 0xc0, 0x49, 0xb7, 0xb5, 0x7f, 0x0e, 0x83, 0xcd, 0x86, 0xf4, 0xd8,
	0xd5, 0xa2, 0x8c, 0xcd, 0x5b, 0xe1, 0x50, 0x53, 0x91, 0x43, 0xb0, 0x93, 0x22, 0xc5, 0x2c, 0x86,
	0x54, 0x1f, 0x09, 0x01, 0x47, 0x3f, 0x03, 0x33, 0x70, 0x28, 0x9e, 0x7d, 0x06, 0xc3, 0xed, 0xca,
	0x34, 0xf0, 0x59, 0x8a, 0xd2, 0x5c, 0x84, 0x67, 0x32, 0x86, 0xae, 0x12, 0x26, 0xd1, 0xae, 0x12,
	0xc4, 0x85, 0x3e, 0x4b, 0xda, 0xf9, 0xda, 0x7b, 0x36, 0xe5, 0xad, 0xfc, 0x9d, 0xdb, 0xf9, 0xfb,
	0xdf, 0x2d, 0xe8, 0xb5, 0xeb, 0xbd, 0xb3, 0x57, 0x7d, 0x69, 0x9a, 0x4a, 0xde, 0x34, 0xa6, 0xdf,
	0x4d, 0xf9, 0x6f, 0xea, 0xf6, 0x7f, 0xa9, 0x1f, 0xc3, 0x28, 0x16, 0x42, 0x4d, 0x1b, 0xc5, 0x66,
	0x3c, 0x35, 0x8f, 0x06, 0x2d, 0x5d, 0xa2, 0xa2, 0x73, 0xcc, 0x97, 0xa9, 0x14, 0x19, 0xaf, 0xcc,
	0xd2, 0xb6, 0xb5, 0xee, 0x87, 0x95, 0x35, 0x97, 0xdc, 0xec, 0xca, 0x54, 0x3a, 0x88, 0x2b, 0x31,
	0x6f, 0x37, 0xe3, 0x50, 0x3c, 0xbf, 0xbd, 0xf8, 0xb1, 0xf2, 0xac, 0xeb, 0x95, 0x67, 0xfd, 0x5a,
	0x79, 0xd6, 0xd7, 0xb5, 0xd7, 0xb9, 0x5e, 0x7b, 0x9d, 0x9f, 0x6b, 0xaf, 0xf3, 0x29, 0xca, 0x0a,
	0x95, 0x2f, 0xe2, 0x30, 0x11, 0x65, 0x84, 0xef, 0x76, 0x22, 0xaa, 0x4c, 0x77, 0x1f, 0x65, 0xe2,
	0x79, 0xfb, 0xf9, 0x7f, 0x31, 0x3f, 0x00, 0xb5, 0xac, 0x79, 0x13, 0xf7, 0xf0, 0xb3, 0x7f, 0xf1,
	0x27, 0x00, 0x00, 0xff, 0xff, 0xd3, 0xa2, 0xfb, 0xf9, 0x1c, 0x04, 0x00, 0x00,
}

func (m *GraphSnapshot) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GraphSnapshot) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GraphSnapshot) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Neurons) > 0 {
		for iNdEx := len(m.Neurons) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Neurons[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSnapshot(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Links) > 0 {
		for iNdEx := len(m.Links) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Links[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSnapshot(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Particles) > 0 {
		for iNdEx := len(m.Particles) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Particles[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSnapshot(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Header != nil {
		{
			size, err := m.Header.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSnapshot(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GraphSnapshotHeader) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GraphSnapshotHeader) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GraphSnapshotHeader) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Checksum) > 0 {
		i -= len(m.Checksum)
		copy(dAtA[i:], m.Checksum)
		i = encodeVarintSnapshot(dAtA, i, uint64(len(m.Checksum)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.RankMerkleRoot) > 0 {
		i -= len(m.RankMerkleRoot)
		copy(dAtA[i:], m.RankMerkleRoot)
		i = encodeVarintSnapshot(dAtA, i, uint64(len(m.RankMerkleRoot)))
		i--
		dAtA[i] = 0x3a
	}
	if m.NeuronsCount != 0 {
		i = encodeVarintSnapshot(dAtA, i, uint64(m.NeuronsCount))
		i--
		dAtA[i] = 0x30
	}
	if m.LinksCount != 0 {
		i = encodeVarintSnapshot(dAtA, i, uint64(m.LinksCount))
		i--
		dAtA[i] = 0x28
	}
	if m.ParticlesCount != 0 {
		i = encodeVarintSnapshot(dAtA, i, uint64(m.ParticlesCount))
		i--
		dAtA[i] = 0x20
	}
	if m.Timestamp != 0 {
		i = encodeVarintSnapshot(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x18
	}
	if m.Height != 0 {
		i = encodeVarintSnapshot(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintSnapshot(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Particle) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Particle) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Particle) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Rank != 0 {
		i = encodeVarintSnapshot(dAtA, i, uint64(m.Rank))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Cid) > 0 {
		i -= len(m.Cid)
		copy(dAtA[i:], m.Cid)
		i = encodeVarintSnapshot(dAtA, i, uint64(len(m.Cid)))
		i--
		dAtA[i] = 0x12
	}
	if m.Number != 0 {
		i = encodeVarintSnapshot(dAtA, i, uint64(m.Number))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Cyberlink) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Cyberlink) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Cyberlink) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Height != 0 {
		i = encodeVarintSnapshot(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x20
	}
	if m.Account != 0 {
		i = encodeVarintSnapshot(dAtA, i, uint64(m.Account))
		i--
		dAtA[i] = 0x18
	}
	if m.To != 0 {
		i = encodeVarintSnapshot(dAtA, i, uint64(m.To))
		i--
		dAtA[i] = 0x10
	}
	if m.From != 0 {
		i = encodeVarintSnapshot(dAtA, i, uint64(m.From))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Neuron) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Neuron) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Neuron) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Volt != 0 {
		i = encodeVarintSnapshot(dAtA, i, uint64(m.Volt))
		i--
		dAtA[i] = 0x38
	}
	if m.Ampere != 0 {
		i = encodeVarintSnapshot(dAtA, i, uint64(m.Ampere))
		i--
		dAtA[i] = 0x30
	}
	if m.Hydrogen != 0 {
		i = encodeVarintSnapshot(dAtA, i, uint64(m.Hydrogen))
		i--
		dAtA[i] = 0x28
	}
	if m.BootStaked != 0 {
		i = encodeVarintSnapshot(dAtA, i, uint64(m.BootStaked))
		i--
		dAtA[i] = 0x20
	}
	if m.LinksCount != 0 {
		i = encodeVarintSnapshot(dAtA, i, uint64(m.LinksCount))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintSnapshot(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if m.Number != 0 {
		i = encodeVarintSnapshot(dAtA, i, uint64(m.Number))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintSnapshot(dAtA []byte, offset int, v uint64) int {
	offset -= sovSnapshot(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GraphSnapshot) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Header != nil {
		l = m.Header.Size()
		n += 1 + l + sovSnapshot(uint64(l))
	}
	if len(m.Particles) > 0 {
		for _, e := range m.Particles {
			l = e.Size()
			n += 1 + l + sovSnapshot(uint64(l))
		}
	}
	if len(m.Links) > 0 {
		for _, e := range m.Links {
			l = e.Size()
			n += 1 + l + sovSnapshot(uint64(l))
		}
	}
	if len(m.Neurons) > 0 {
		for _, e := range m.Neurons {
			l = e.Size()
			n += 1 + l + sovSnapshot(uint64(l))
		}
	}
	return n
}

func (m *GraphSnapshotHeader) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovSnapshot(uint64(l))
	}
	if m.Height != 0 {
		n += 1 + sovSnapshot(uint64(m.Height))
	}
	if m.Timestamp != 0 {
		n += 1 + sovSnapshot(uint64(m.Timestamp))
	}
	if m.ParticlesCount != 0 {
		n += 1 + sovSnapshot(uint64(m.ParticlesCount))
	}
	if m.LinksCount != 0 {
		n += 1 + sovSnapshot(uint64(m.LinksCount))
	}
	if m.NeuronsCount != 0 {
		n += 1 + sovSnapshot(uint64(m.NeuronsCount))
	}
	l = len(m.RankMerkleRoot)
	if l > 0 {
		n += 1 + l + sovSnapshot(uint64(l))
	}
	l = len(m.Checksum)
	if l > 0 {
		n += 1 + l + sovSnapshot(uint64(l))
	}
	return n
}

func (m *Particle) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Number != 0 {
		n += 1 + sovSnapshot(uint64(m.Number))
	}
	l = len(m.Cid)
	if l > 0 {
		n += 1 + l + sovSnapshot(uint64(l))
	}
	if m.Rank != 0 {
		n += 1 + sovSnapshot(uint64(m.Rank))
	}
	return n
}

func (m *Cyberlink) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.From != 0 {
		n += 1 + sovSnapshot(uint64(m.From))
	}
	if m.To != 0 {
		n += 1 + sovSnapshot(uint64(m.To))
	}
	if m.Account != 0 {
		n += 1 + sovSnapshot(uint64(m.Account))
	}
	if m.Height != 0 {
		n += 1 + sovSnapshot(uint64(m.Height))
	}
	return n
}

func (m *Neuron) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Number != 0 {
		n += 1 + sovSnapshot(uint64(m.Number))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovSnapshot(uint64(l))
	}
	if m.LinksCount != 0 {
		n += 1 + sovSnapshot(uint64(m.LinksCount))
	}
	if m.BootStaked != 0 {
		n += 1 + sovSnapshot(uint64(m.BootStaked))
	}
	if m.Hydrogen != 0 {
		n += 1 + sovSnapshot(uint64(m.Hydrogen))
	}
	if m.Ampere != 0 {
		n += 1 + sovSnapshot(uint64(m.Ampere))
	}
	if m.Volt != 0 {
		n += 1 + sovSnapshot(uint64(m.Volt))
	}
	return n
}

func sovSnapshot(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSnapshot(x uint64) (n int) {
	return sovSnapshot(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GraphSnapshot) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSnapshot
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GraphSnapshot: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GraphSnapshot: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Header", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Header == nil {
				m.Header = &GraphSnapshotHeader{}
			}
			if err := m.Header.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Particles", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Particles = append(m.Particles, &Particle{})
			if err := m.Particles[len(m.Particles)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Links", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Links = append(m.Links, &Cyberlink{})
			if err := m.Links[len(m.Links)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Neurons", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Neurons = append(m.Neurons, &Neuron{})
			if err := m.Neurons[len(m.Neurons)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSnapshot(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSnapshot
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GraphSnapshotHeader) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSnapshot
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GraphSnapshotHeader: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GraphSnapshotHeader: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParticlesCount", wireType)
			}
			m.ParticlesCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ParticlesCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LinksCount", wireType)
			}
			m.LinksCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LinksCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NeuronsCount", wireType)
			}
			m.NeuronsCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NeuronsCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RankMerkleRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RankMerkleRoot = append(m.RankMerkleRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.RankMerkleRoot == nil {
				m.RankMerkleRoot = []byte{}
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Checksum", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Checksum = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSnapshot(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSnapshot
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Particle) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSnapshot
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Particle: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Particle: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Number", wireType)
			}
			m.Number = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Number |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Cid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rank", wireType)
			}
			m.Rank = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Rank |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSnapshot(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSnapshot
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Cyberlink) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSnapshot
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Cyberlink: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Cyberlink: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field From", wireType)
			}
			m.From = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.From |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field To", wireType)
			}
			m.To = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.To |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			m.Account = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Account |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSnapshot(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSnapshot
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Neuron) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSnapshot
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Neuron: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Neuron: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Number", wireType)
			}
			m.Number = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Number |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSnapshot
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSnapshot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LinksCount", wireType)
			}
			m.LinksCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LinksCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BootStaked", wireType)
			}
			m.BootStaked = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BootStaked |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hydrogen", wireType)
			}
			m.Hydrogen = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Hydrogen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ampere", wireType)
			}
			m.Ampere = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Ampere |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Volt", wireType)
			}
			m.Volt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Volt |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSnapshot(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSnapshot
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSnapshot(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSnapshot
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSnapshot
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSnapshot
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSnapshot
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSnapshot
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSnapshot        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSnapshot          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSnapshot = fmt.Errorf("proto: unexpected end of group")
)
