// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cyber/graph/v1beta1/sync_query.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryLatestSnapshotRequest struct {
}

func (m *QueryLatestSnapshotRequest) Reset()         { *m = QueryLatestSnapshotRequest{} }
func (m *QueryLatestSnapshotRequest) String() string { return proto.CompactTextString(m) }
func (*QueryLatestSnapshotRequest) ProtoMessage()    {}
func (*QueryLatestSnapshotRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_570b11306a35cf7a, []int{0}
}
func (m *QueryLatestSnapshotRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLatestSnapshotRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLatestSnapshotRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLatestSnapshotRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLatestSnapshotRequest.Merge(m, src)
}
func (m *QueryLatestSnapshotRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryLatestSnapshotRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLatestSnapshotRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLatestSnapshotRequest proto.InternalMessageInfo

type QueryLatestSnapshotResponse struct {
	ChainId              string `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Height               uint64 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Timestamp            int64  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ParticlesCount       uint64 `protobuf:"varint,4,opt,name=particles_count,json=particlesCount,proto3" json:"particles_count,omitempty"`
	LinksCount           uint64 `protobuf:"varint,5,opt,name=links_count,json=linksCount,proto3" json:"links_count,omitempty"`
	NeuronsCount         uint64 `protobuf:"varint,6,opt,name=neurons_count,json=neuronsCount,proto3" json:"neurons_count,omitempty"`
	RankMerkleRoot       []byte `protobuf:"bytes,7,opt,name=rank_merkle_root,json=rankMerkleRoot,proto3" json:"rank_merkle_root,omitempty"`
	ProtobufUrl          string `protobuf:"bytes,8,opt,name=protobuf_url,json=protobufUrl,proto3" json:"protobuf_url,omitempty"`
	ParquetParticlesUrl  string `protobuf:"bytes,9,opt,name=parquet_particles_url,json=parquetParticlesUrl,proto3" json:"parquet_particles_url,omitempty"`
	ParquetLinksUrl      string `protobuf:"bytes,10,opt,name=parquet_links_url,json=parquetLinksUrl,proto3" json:"parquet_links_url,omitempty"`
	ParquetNeuronsUrl    string `protobuf:"bytes,11,opt,name=parquet_neurons_url,json=parquetNeuronsUrl,proto3" json:"parquet_neurons_url,omitempty"`
	ProtobufSize         uint64 `protobuf:"varint,12,opt,name=protobuf_size,json=protobufSize,proto3" json:"protobuf_size,omitempty"`
	ParquetParticlesSize uint64 `protobuf:"varint,13,opt,name=parquet_particles_size,json=parquetParticlesSize,proto3" json:"parquet_particles_size,omitempty"`
	ParquetLinksSize     uint64 `protobuf:"varint,14,opt,name=parquet_links_size,json=parquetLinksSize,proto3" json:"parquet_links_size,omitempty"`
	ParquetNeuronsSize   uint64 `protobuf:"varint,15,opt,name=parquet_neurons_size,json=parquetNeuronsSize,proto3" json:"parquet_neurons_size,omitempty"`
	ProtobufChecksum     string `protobuf:"bytes,16,opt,name=protobuf_checksum,json=protobufChecksum,proto3" json:"protobuf_checksum,omitempty"`
}

func (m *QueryLatestSnapshotResponse) Reset()         { *m = QueryLatestSnapshotResponse{} }
func (m *QueryLatestSnapshotResponse) String() string { return proto.CompactTextString(m) }
func (*QueryLatestSnapshotResponse) ProtoMessage()    {}
func (*QueryLatestSnapshotResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_570b11306a35cf7a, []int{1}
}
func (m *QueryLatestSnapshotResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLatestSnapshotResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLatestSnapshotResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLatestSnapshotResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLatestSnapshotResponse.Merge(m, src)
}
func (m *QueryLatestSnapshotResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryLatestSnapshotResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLatestSnapshotResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLatestSnapshotResponse proto.InternalMessageInfo

func (m *QueryLatestSnapshotResponse) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *QueryLatestSnapshotResponse) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *QueryLatestSnapshotResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *QueryLatestSnapshotResponse) GetParticlesCount() uint64 {
	if m != nil {
		return m.ParticlesCount
	}
	return 0
}

func (m *QueryLatestSnapshotResponse) GetLinksCount() uint64 {
	if m != nil {
		return m.LinksCount
	}
	return 0
}

func (m *QueryLatestSnapshotResponse) GetNeuronsCount() uint64 {
	if m != nil {
		return m.NeuronsCount
	}
	return 0
}

func (m *QueryLatestSnapshotResponse) GetRankMerkleRoot() []byte {
	if m != nil {
		return m.RankMerkleRoot
	}
	return nil
}

func (m *QueryLatestSnapshotResponse) GetProtobufUrl() string {
	if m != nil {
		return m.ProtobufUrl
	}
	return ""
}

func (m *QueryLatestSnapshotResponse) GetParquetParticlesUrl() string {
	if m != nil {
		return m.ParquetParticlesUrl
	}
	return ""
}

func (m *QueryLatestSnapshotResponse) GetParquetLinksUrl() string {
	if m != nil {
		return m.ParquetLinksUrl
	}
	return ""
}

func (m *QueryLatestSnapshotResponse) GetParquetNeuronsUrl() string {
	if m != nil {
		return m.ParquetNeuronsUrl
	}
	return ""
}

func (m *QueryLatestSnapshotResponse) GetProtobufSize() uint64 {
	if m != nil {
		return m.ProtobufSize
	}
	return 0
}

func (m *QueryLatestSnapshotResponse) GetParquetParticlesSize() uint64 {
	if m != nil {
		return m.ParquetParticlesSize
	}
	return 0
}

func (m *QueryLatestSnapshotResponse) GetParquetLinksSize() uint64 {
	if m != nil {
		return m.ParquetLinksSize
	}
	return 0
}

func (m *QueryLatestSnapshotResponse) GetParquetNeuronsSize() uint64 {
	if m != nil {
		return m.ParquetNeuronsSize
	}
	return 0
}

func (m *QueryLatestSnapshotResponse) GetProtobufChecksum() string {
	if m != nil {
		return m.ProtobufChecksum
	}
	return ""
}

type SubscribeGraphRequest struct {
	SinceHeight uint64 `protobuf:"varint,1,opt,name=since_height,json=sinceHeight,proto3" json:"since_height,omitempty"`
}

func (m *SubscribeGraphRequest) Reset()         { *m = SubscribeGraphRequest{} }
func (m *SubscribeGraphRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeGraphRequest) ProtoMessage()    {}
func (*SubscribeGraphRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_570b11306a35cf7a, []int{2}
}
func (m *SubscribeGraphRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SubscribeGraphRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SubscribeGraphRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SubscribeGraphRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeGraphRequest.Merge(m, src)
}
func (m *SubscribeGraphRequest) XXX_Size() int {
	return m.Size()
}
func (m *SubscribeGraphRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeGraphRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeGraphRequest proto.InternalMessageInfo

func (m *SubscribeGraphRequest) GetSinceHeight() uint64 {
	if m != nil {
		return m.SinceHeight
	}
	return 0
}

type GraphUpdate struct {
	FromHeight     uint64       `protobuf:"varint,1,opt,name=from_height,json=fromHeight,proto3" json:"from_height,omitempty"`
	ToHeight       uint64       `protobuf:"varint,2,opt,name=to_height,json=toHeight,proto3" json:"to_height,omitempty"`
	Timestamp      int64        `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	NewParticles   []*Particle  `protobuf:"bytes,4,rep,name=new_particles,json=newParticles,proto3" json:"new_particles,omitempty"`
	NewLinks       []*Cyberlink `protobuf:"bytes,5,rep,name=new_links,json=newLinks,proto3" json:"new_links,omitempty"`
	NewNeurons     []*Neuron    `protobuf:"bytes,6,rep,name=new_neurons,json=newNeurons,proto3" json:"new_neurons,omitempty"`
	RankUpdates    []*RankDelta `protobuf:"bytes,7,rep,name=rank_updates,json=rankUpdates,proto3" json:"rank_updates,omitempty"`
	TotalParticles uint64       `protobuf:"varint,8,opt,name=total_particles,json=totalParticles,proto3" json:"total_particles,omitempty"`
	TotalLinks     uint64       `protobuf:"varint,9,opt,name=total_links,json=totalLinks,proto3" json:"total_links,omitempty"`
	TotalNeurons   uint64       `protobuf:"varint,10,opt,name=total_neurons,json=totalNeurons,proto3" json:"total_neurons,omitempty"`
}

func (m *GraphUpdate) Reset()         { *m = GraphUpdate{} }
func (m *GraphUpdate) String() string { return proto.CompactTextString(m) }
func (*GraphUpdate) ProtoMessage()    {}
func (*GraphUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_570b11306a35cf7a, []int{3}
}
func (m *GraphUpdate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GraphUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GraphUpdate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GraphUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphUpdate.Merge(m, src)
}
func (m *GraphUpdate) XXX_Size() int {
	return m.Size()
}
func (m *GraphUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_GraphUpdate proto.InternalMessageInfo

func (m *GraphUpdate) GetFromHeight() uint64 {
	if m != nil {
		return m.FromHeight
	}
	return 0
}

func (m *GraphUpdate) GetToHeight() uint64 {
	if m != nil {
		return m.ToHeight
	}
	return 0
}

func (m *GraphUpdate) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *GraphUpdate) GetNewParticles() []*Particle {
	if m != nil {
		return m.NewParticles
	}
	return nil
}

func (m *GraphUpdate) GetNewLinks() []*Cyberlink {
	if m != nil {
		return m.NewLinks
	}
	return nil
}

func (m *GraphUpdate) GetNewNeurons() []*Neuron {
	if m != nil {
		return m.NewNeurons
	}
	return nil
}

func (m *GraphUpdate) GetRankUpdates() []*RankDelta {
	if m != nil {
		return m.RankUpdates
	}
	return nil
}

func (m *GraphUpdate) GetTotalParticles() uint64 {
	if m != nil {
		return m.TotalParticles
	}
	return 0
}

func (m *GraphUpdate) GetTotalLinks() uint64 {
	if m != nil {
		return m.TotalLinks
	}
	return 0
}

func (m *GraphUpdate) GetTotalNeurons() uint64 {
	if m != nil {
		return m.TotalNeurons
	}
	return 0
}

type RankDelta struct {
	Particle uint64 `protobuf:"varint,1,opt,name=particle,proto3" json:"particle,omitempty"`
	Rank     uint64 `protobuf:"varint,2,opt,name=rank,proto3" json:"rank,omitempty"`
}

func (m *RankDelta) Reset()         { *m = RankDelta{} }
func (m *RankDelta) String() string { return proto.CompactTextString(m) }
func (*RankDelta) ProtoMessage()    {}
func (*RankDelta) Descriptor() ([]byte, []int) {
	return fileDescriptor_570b11306a35cf7a, []int{4}
}
func (m *RankDelta) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RankDelta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RankDelta.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RankDelta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RankDelta.Merge(m, src)
}
func (m *RankDelta) XXX_Size() int {
	return m.Size()
}
func (m *RankDelta) XXX_DiscardUnknown() {
	xxx_messageInfo_RankDelta.DiscardUnknown(m)
}

var xxx_messageInfo_RankDelta proto.InternalMessageInfo

func (m *RankDelta) GetParticle() uint64 {
	if m != nil {
		return m.Particle
	}
	return 0
}

func (m *RankDelta) GetRank() uint64 {
	if m != nil {
		return m.Rank
	}
	return 0
}

func init() {
	proto.RegisterType((*QueryLatestSnapshotRequest)(nil), "cyber.graph.v1beta1.QueryLatestSnapshotRequest")
	proto.RegisterType((*QueryLatestSnapshotResponse)(nil), "cyber.graph.v1beta1.QueryLatestSnapshotResponse")
	proto.RegisterType((*SubscribeGraphRequest)(nil), "cyber.graph.v1beta1.SubscribeGraphRequest")
	proto.RegisterType((*GraphUpdate)(nil), "cyber.graph.v1beta1.GraphUpdate")
	proto.RegisterType((*RankDelta)(nil), "cyber.graph.v1beta1.RankDelta")
}

func init() {
	proto.RegisterFile("cyber/graph/v1beta1/sync_query.proto", fileDescriptor_570b11306a35cf7a)
}

var fileDescriptor_570b11306a35cf7a = []byte{
	// 838 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x4d, 0x73, 0xdb, 0x44,
	0x18, 0x8e, 0x62, 0xc7, 0xb1, 0x5f, 0xd9, 0x8e, 0xbb, 0xfd, 0x18, 0xe1, 0x04, 0xd7, 0x28, 0x1d,
	0x6a, 0x4a, 0xb1, 0xd2, 0xc0, 0x89, 0x72, 0xa1, 0x61, 0x86, 0x76, 0xa6, 0x30, 0x20, 0x4f, 0x2f,
	0x5c, 0x34, 0x6b, 0x65, 0x6b, 0x6b, 0x2c, 0xef, 0x2a, 0xda, 0x15, 0xc6, 0x3d, 0xf2, 0x0b, 0x60,
	0xf8, 0x05, 0xf0, 0x6b, 0x7a, 0xec, 0x0c, 0x17, 0x86, 0x13, 0x93, 0xf0, 0x43, 0x98, 0x7d, 0x57,
	0xb2, 0xe3, 0xa2, 0x66, 0x72, 0x93, 0x9e, 0x7d, 0x9e, 0x77, 0x9f, 0xf7, 0x6b, 0xe1, 0x5e, 0xb8,
	0x1c, 0xb3, 0xd4, 0x9b, 0xa4, 0x34, 0x99, 0x7a, 0x3f, 0x3e, 0x1a, 0x33, 0x45, 0x1f, 0x79, 0x72,
	0xc9, 0xc3, 0xe0, 0x2c, 0x63, 0xe9, 0x72, 0x98, 0xa4, 0x42, 0x09, 0x72, 0x13, 0x59, 0x43, 0x64,
	0x0d, 0x73, 0x56, 0xf7, 0x60, 0x22, 0xc4, 0x24, 0x66, 0x1e, 0x4d, 0x22, 0x8f, 0x72, 0x2e, 0x14,
	0x55, 0x91, 0xe0, 0xd2, 0x48, 0xba, 0x6e, 0x69, 0x60, 0x4e, 0x13, 0x39, 0x15, 0xca, 0x70, 0xdc,
	0x03, 0xe8, 0x7e, 0xaf, 0x6f, 0x79, 0x4e, 0x15, 0x93, 0x6a, 0x94, 0x1f, 0xfa, 0xec, 0x2c, 0x63,
	0x52, 0xb9, 0x7f, 0xec, 0xc0, 0x7e, 0xe9, 0xb1, 0x4c, 0x04, 0x97, 0x8c, 0xbc, 0x07, 0xf5, 0x70,
	0x4a, 0x23, 0x1e, 0x44, 0xa7, 0x8e, 0xd5, 0xb7, 0x06, 0x0d, 0x7f, 0x17, 0xff, 0x9f, 0x9d, 0x92,
	0x3b, 0x50, 0x9b, 0xb2, 0x68, 0x32, 0x55, 0xce, 0x76, 0xdf, 0x1a, 0x54, 0xfd, 0xfc, 0x8f, 0x1c,
	0x40, 0x43, 0x45, 0x73, 0x26, 0x15, 0x9d, 0x27, 0x4e, 0xa5, 0x6f, 0x0d, 0x2a, 0xfe, 0x1a, 0x20,
	0xf7, 0x61, 0x2f, 0xa1, 0xa9, 0x8a, 0xc2, 0x98, 0xc9, 0x20, 0x14, 0x19, 0x57, 0x4e, 0x15, 0xe5,
	0xed, 0x15, 0x7c, 0xa2, 0x51, 0x72, 0x17, 0xec, 0x38, 0xe2, 0xb3, 0x82, 0xb4, 0x83, 0x24, 0x40,
	0xc8, 0x10, 0x0e, 0xa1, 0xc5, 0x59, 0x96, 0x0a, 0x5e, 0x50, 0x6a, 0x48, 0x69, 0xe6, 0xa0, 0x21,
	0x0d, 0xa0, 0x93, 0x52, 0x3e, 0x0b, 0xe6, 0x2c, 0x9d, 0xc5, 0x2c, 0x48, 0x85, 0x50, 0xce, 0x6e,
	0xdf, 0x1a, 0x34, 0xfd, 0xb6, 0xc6, 0xbf, 0x41, 0xd8, 0x17, 0x42, 0x91, 0x0f, 0xa0, 0x89, 0x05,
	0x1b, 0x67, 0x2f, 0x83, 0x2c, 0x8d, 0x9d, 0x3a, 0x66, 0x6b, 0x17, 0xd8, 0x8b, 0x34, 0x26, 0xc7,
	0x70, 0x3b, 0xa1, 0xe9, 0x59, 0xc6, 0x54, 0xb0, 0xce, 0x41, 0x73, 0x1b, 0xc8, 0xbd, 0x99, 0x1f,
	0x7e, 0x57, 0x9c, 0x69, 0xcd, 0x03, 0xb8, 0x51, 0x68, 0x4c, 0x3a, 0x9a, 0x0f, 0xc8, 0xdf, 0xcb,
	0x0f, 0x9e, 0x6b, 0x5c, 0x73, 0x87, 0x50, 0x84, 0x08, 0x8a, 0xcc, 0x34, 0xdb, 0x46, 0x76, 0x11,
	0xe6, 0x5b, 0x73, 0xa2, 0xf9, 0x87, 0xd0, 0x5a, 0x59, 0x96, 0xd1, 0x2b, 0xe6, 0x34, 0x4d, 0x05,
	0x0a, 0x70, 0x14, 0xbd, 0x62, 0xe4, 0x33, 0xb8, 0xf3, 0x7f, 0xd3, 0xc8, 0x6e, 0x21, 0xfb, 0xd6,
	0xdb, 0xae, 0x51, 0xf5, 0x10, 0xc8, 0xa6, 0x6d, 0x54, 0xb4, 0x51, 0xd1, 0xb9, 0xec, 0x1b, 0xd9,
	0x47, 0x70, 0xeb, 0x6d, 0xe3, 0xc8, 0xdf, 0x43, 0x3e, 0xd9, 0x74, 0x8e, 0x8a, 0x8f, 0xe1, 0xc6,
	0xca, 0x7a, 0x38, 0x65, 0xe1, 0x4c, 0x66, 0x73, 0xa7, 0x83, 0x89, 0x76, 0x8a, 0x83, 0x93, 0x1c,
	0x77, 0x3f, 0x87, 0xdb, 0xa3, 0x6c, 0x2c, 0xc3, 0x34, 0x1a, 0xb3, 0xaf, 0xf5, 0xac, 0xe7, 0xd3,
	0xab, 0x7b, 0x26, 0x23, 0x1e, 0xb2, 0x20, 0x1f, 0x44, 0x0b, 0xef, 0xb3, 0x11, 0x7b, 0x8a, 0x90,
	0xfb, 0x77, 0x05, 0x6c, 0xd4, 0xbc, 0x48, 0x4e, 0xa9, 0x62, 0x7a, 0xac, 0x5e, 0xa6, 0x62, 0xbe,
	0xa9, 0x00, 0x0d, 0x19, 0x01, 0xd9, 0x87, 0x86, 0x12, 0xc1, 0xc6, 0x64, 0xd7, 0x95, 0x78, 0x7a,
	0x9d, 0xd9, 0x7e, 0xa2, 0x27, 0x72, 0xb1, 0x2e, 0xb3, 0x53, 0xed, 0x57, 0x06, 0xf6, 0xf1, 0xfb,
	0xc3, 0x92, 0xcd, 0x1e, 0x16, 0xf5, 0xd6, 0x03, 0xbb, 0x58, 0x15, 0x9f, 0x3c, 0x86, 0x86, 0x8e,
	0x81, 0x45, 0x77, 0x76, 0x50, 0xdf, 0x2b, 0xd5, 0x9f, 0x68, 0x4c, 0xd3, 0xfc, 0x3a, 0x67, 0x0b,
	0xec, 0x05, 0xf9, 0x02, 0x6c, 0x2d, 0xce, 0x7b, 0xe0, 0xd4, 0x50, 0xbe, 0x5f, 0x2a, 0x37, 0xcd,
	0xf0, 0x81, 0xb3, 0x45, 0xde, 0x17, 0xf2, 0x25, 0x34, 0x71, 0x57, 0x32, 0xac, 0x94, 0x74, 0x76,
	0xaf, 0xb8, 0xdd, 0xa7, 0x7c, 0xf6, 0x15, 0x8b, 0x15, 0xf5, 0x6d, 0xad, 0x31, 0xc5, 0x95, 0x7a,
	0xbb, 0x95, 0x50, 0x34, 0xbe, 0x54, 0x83, 0xba, 0xd9, 0x6e, 0x84, 0xd7, 0x69, 0xde, 0x05, 0xdb,
	0x10, 0x4d, 0xa2, 0x0d, 0xd3, 0x06, 0x84, 0x4c, 0x2a, 0x87, 0xd0, 0x32, 0x84, 0x22, 0x19, 0x30,
	0xb3, 0x8d, 0x60, 0xee, 0xd8, 0x7d, 0x0c, 0x8d, 0x95, 0x11, 0xd2, 0x85, 0x7a, 0x71, 0x6b, 0xde,
	0xd6, 0xd5, 0x3f, 0x21, 0x50, 0xd5, 0x36, 0xf3, 0x7e, 0xe2, 0xf7, 0xf1, 0xeb, 0x6d, 0x68, 0xe3,
	0x64, 0x8c, 0x96, 0x3c, 0xc4, 0x37, 0x90, 0xfc, 0x6e, 0x41, 0x7b, 0xf3, 0x21, 0x24, 0x5e, 0x69,
	0xfa, 0xef, 0x7e, 0x51, 0xbb, 0x47, 0xd7, 0x17, 0x98, 0x37, 0xd6, 0x7d, 0xf8, 0xf3, 0x9f, 0xff,
	0xfe, 0xb6, 0xfd, 0x21, 0xb9, 0xe7, 0x5d, 0xf5, 0x9c, 0x7b, 0x31, 0xaa, 0xc9, 0xaf, 0x16, 0xb4,
	0x37, 0xb7, 0x81, 0x3c, 0x28, 0xbd, 0xb2, 0x74, 0x65, 0xba, 0xfd, 0x52, 0xee, 0xa5, 0x0d, 0x71,
	0x3d, 0xb4, 0xf3, 0x11, 0xb9, 0x7f, 0xb5, 0x1d, 0x59, 0x84, 0x3f, 0xb2, 0x9e, 0x3c, 0x7b, 0x7d,
	0xde, 0xb3, 0xde, 0x9c, 0xf7, 0xac, 0x7f, 0xce, 0x7b, 0xd6, 0x2f, 0x17, 0xbd, 0xad, 0x37, 0x17,
	0xbd, 0xad, 0xbf, 0x2e, 0x7a, 0x5b, 0x3f, 0x78, 0x93, 0x48, 0x4d, 0xb3, 0xf1, 0x30, 0x14, 0x73,
	0x13, 0x2e, 0x14, 0x7c, 0x92, 0x32, 0x29, 0xbd, 0x89, 0xf8, 0xc4, 0xc4, 0xff, 0x29, 0xbf, 0x41,
	0x2d, 0x13, 0x26, 0xc7, 0x35, 0xdc, 0xfe, 0x4f, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x46, 0xc7,
	0xa0, 0x33, 0x34, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GraphSyncQueryClient is the client API for GraphSyncQuery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GraphSyncQueryClient interface {
	LatestSnapshot(ctx context.Context, in *QueryLatestSnapshotRequest, opts ...grpc.CallOption) (*QueryLatestSnapshotResponse, error)
	SubscribeGraph(ctx context.Context, in *SubscribeGraphRequest, opts ...grpc.CallOption) (GraphSyncQuery_SubscribeGraphClient, error)
}

type graphSyncQueryClient struct {
	cc grpc1.ClientConn
}

func NewGraphSyncQueryClient(cc grpc1.ClientConn) GraphSyncQueryClient {
	return &graphSyncQueryClient{cc}
}

func (c *graphSyncQueryClient) LatestSnapshot(ctx context.Context, in *QueryLatestSnapshotRequest, opts ...grpc.CallOption) (*QueryLatestSnapshotResponse, error) {
	out := new(QueryLatestSnapshotResponse)
	err := c.cc.Invoke(ctx, "/cyber.graph.v1beta1.GraphSyncQuery/LatestSnapshot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphSyncQueryClient) SubscribeGraph(ctx context.Context, in *SubscribeGraphRequest, opts ...grpc.CallOption) (GraphSyncQuery_SubscribeGraphClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GraphSyncQuery_serviceDesc.Streams[0], "/cyber.graph.v1beta1.GraphSyncQuery/SubscribeGraph", opts...)
	if err != nil {
		return nil, err
	}
	x := &graphSyncQuerySubscribeGraphClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GraphSyncQuery_SubscribeGraphClient interface {
	Recv() (*GraphUpdate, error)
	grpc.ClientStream
}

type graphSyncQuerySubscribeGraphClient struct {
	grpc.ClientStream
}

func (x *graphSyncQuerySubscribeGraphClient) Recv() (*GraphUpdate, error) {
	m := new(GraphUpdate)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GraphSyncQueryServer is the server API for GraphSyncQuery service.
type GraphSyncQueryServer interface {
	LatestSnapshot(context.Context, *QueryLatestSnapshotRequest) (*QueryLatestSnapshotResponse, error)
	SubscribeGraph(*SubscribeGraphRequest, GraphSyncQuery_SubscribeGraphServer) error
}

// UnimplementedGraphSyncQueryServer can be embedded to have forward compatible implementations.
type UnimplementedGraphSyncQueryServer struct {
}

func (*UnimplementedGraphSyncQueryServer) LatestSnapshot(ctx context.Context, req *QueryLatestSnapshotRequest) (*QueryLatestSnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LatestSnapshot not implemented")
}
func (*UnimplementedGraphSyncQueryServer) SubscribeGraph(req *SubscribeGraphRequest, srv GraphSyncQuery_SubscribeGraphServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeGraph not implemented")
}

func RegisterGraphSyncQueryServer(s grpc1.Server, srv GraphSyncQueryServer) {
	s.RegisterService(&_GraphSyncQuery_serviceDesc, srv)
}

func _GraphSyncQuery_LatestSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLatestSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphSyncQueryServer).LatestSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cyber.graph.v1beta1.GraphSyncQuery/LatestSnapshot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphSyncQueryServer).LatestSnapshot(ctx, req.(*QueryLatestSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphSyncQuery_SubscribeGraph_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeGraphRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GraphSyncQueryServer).SubscribeGraph(m, &graphSyncQuerySubscribeGraphServer{stream})
}

type GraphSyncQuery_SubscribeGraphServer interface {
	Send(*GraphUpdate) error
	grpc.ServerStream
}

type graphSyncQuerySubscribeGraphServer struct {
	grpc.ServerStream
}

func (x *graphSyncQuerySubscribeGraphServer) Send(m *GraphUpdate) error {
	return x.ServerStream.SendMsg(m)
}

var GraphSyncQuery_serviceDesc = _GraphSyncQuery_serviceDesc
var _GraphSyncQuery_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cyber.graph.v1beta1.GraphSyncQuery",
	HandlerType: (*GraphSyncQueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LatestSnapshot",
			Handler:    _GraphSyncQuery_LatestSnapshot_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeGraph",
			Handler:       _GraphSyncQuery_SubscribeGraph_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cyber/graph/v1beta1/sync_query.proto",
}

func (m *QueryLatestSnapshotRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLatestSnapshotRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLatestSnapshotRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryLatestSnapshotResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLatestSnapshotResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLatestSnapshotResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ProtobufChecksum) > 0 {
		i -= len(m.ProtobufChecksum)
		copy(dAtA[i:], m.ProtobufChecksum)
		i = encodeVarintSyncQuery(dAtA, i, uint64(len(m.ProtobufChecksum)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x82
	}
	if m.ParquetNeuronsSize != 0 {
		i = encodeVarintSyncQuery(dAtA, i, uint64(m.ParquetNeuronsSize))
		i--
		dAtA[i] = 0x78
	}
	if m.ParquetLinksSize != 0 {
		i = encodeVarintSyncQuery(dAtA, i, uint64(m.ParquetLinksSize))
		i--
		dAtA[i] = 0x70
	}
	if m.ParquetParticlesSize != 0 {
		i = encodeVarintSyncQuery(dAtA, i, uint64(m.ParquetParticlesSize))
		i--
		dAtA[i] = 0x68
	}
	if m.ProtobufSize != 0 {
		i = encodeVarintSyncQuery(dAtA, i, uint64(m.ProtobufSize))
		i--
		dAtA[i] = 0x60
	}
	if len(m.ParquetNeuronsUrl) > 0 {
		i -= len(m.ParquetNeuronsUrl)
		copy(dAtA[i:], m.ParquetNeuronsUrl)
		i = encodeVarintSyncQuery(dAtA, i, uint64(len(m.ParquetNeuronsUrl)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.ParquetLinksUrl) > 0 {
		i -= len(m.ParquetLinksUrl)
		copy(dAtA[i:], m.ParquetLinksUrl)
		i = encodeVarintSyncQuery(dAtA, i, uint64(len(m.ParquetLinksUrl)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.ParquetParticlesUrl) > 0 {
		i -= len(m.ParquetParticlesUrl)
		copy(dAtA[i:], m.ParquetParticlesUrl)
		i = encodeVarintSyncQuery(dAtA, i, uint64(len(m.ParquetParticlesUrl)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.ProtobufUrl) > 0 {
		i -= len(m.ProtobufUrl)
		copy(dAtA[i:], m.ProtobufUrl)
		i = encodeVarintSyncQuery(dAtA, i, uint64(len(m.ProtobufUrl)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.RankMerkleRoot) > 0 {
		i -= len(m.RankMerkleRoot)
		copy(dAtA[i:], m.RankMerkleRoot)
		i = encodeVarintSyncQuery(dAtA, i, uint64(len(m.RankMerkleRoot)))
		i--
		dAtA[i] = 0x3a
	}
	if m.NeuronsCount != 0 {
		i = encodeVarintSyncQuery(dAtA, i, uint64(m.NeuronsCount))
		i--
		dAtA[i] = 0x30
	}
	if m.LinksCount != 0 {
		i = encodeVarintSyncQuery(dAtA, i, uint64(m.LinksCount))
		i--
		dAtA[i] = 0x28
	}
	if m.ParticlesCount != 0 {
		i = encodeVarintSyncQuery(dAtA, i, uint64(m.ParticlesCount))
		i--
		dAtA[i] = 0x20
	}
	if m.Timestamp != 0 {
		i = encodeVarintSyncQuery(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x18
	}
	if m.Height != 0 {
		i = encodeVarintSyncQuery(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintSyncQuery(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SubscribeGraphRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SubscribeGraphRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SubscribeGraphRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SinceHeight != 0 {
		i = encodeVarintSyncQuery(dAtA, i, uint64(m.SinceHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *GraphUpdate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GraphUpdate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GraphUpdate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TotalNeurons != 0 {
		i = encodeVarintSyncQuery(dAtA, i, uint64(m.TotalNeurons))
		i--
		dAtA[i] = 0x50
	}
	if m.TotalLinks != 0 {
		i = encodeVarintSyncQuery(dAtA, i, uint64(m.TotalLinks))
		i--
		dAtA[i] = 0x48
	}
	if m.TotalParticles != 0 {
		i = encodeVarintSyncQuery(dAtA, i, uint64(m.TotalParticles))
		i--
		dAtA[i] = 0x40
	}
	if len(m.RankUpdates) > 0 {
		for iNdEx := len(m.RankUpdates) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RankUpdates[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSyncQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.NewNeurons) > 0 {
		for iNdEx := len(m.NewNeurons) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.NewNeurons[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSyncQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.NewLinks) > 0 {
		for iNdEx := len(m.NewLinks) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.NewLinks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSyncQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.NewParticles) > 0 {
		for iNdEx := len(m.NewParticles) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.NewParticles[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSyncQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.Timestamp != 0 {
		i = encodeVarintSyncQuery(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x18
	}
	if m.ToHeight != 0 {
		i = encodeVarintSyncQuery(dAtA, i, uint64(m.ToHeight))
		i--
		dAtA[i] = 0x10
	}
	if m.FromHeight != 0 {
		i = encodeVarintSyncQuery(dAtA, i, uint64(m.FromHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *RankDelta) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RankDelta) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RankDelta) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Rank != 0 {
		i = encodeVarintSyncQuery(dAtA, i, uint64(m.Rank))
		i--
		dAtA[i] = 0x10
	}
	if m.Particle != 0 {
		i = encodeVarintSyncQuery(dAtA, i, uint64(m.Particle))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintSyncQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovSyncQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryLatestSnapshotRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryLatestSnapshotResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovSyncQuery(uint64(l))
	}
	if m.Height != 0 {
		n += 1 + sovSyncQuery(uint64(m.Height))
	}
	if m.Timestamp != 0 {
		n += 1 + sovSyncQuery(uint64(m.Timestamp))
	}
	if m.ParticlesCount != 0 {
		n += 1 + sovSyncQuery(uint64(m.ParticlesCount))
	}
	if m.LinksCount != 0 {
		n += 1 + sovSyncQuery(uint64(m.LinksCount))
	}
	if m.NeuronsCount != 0 {
		n += 1 + sovSyncQuery(uint64(m.NeuronsCount))
	}
	l = len(m.RankMerkleRoot)
	if l > 0 {
		n += 1 + l + sovSyncQuery(uint64(l))
	}
	l = len(m.ProtobufUrl)
	if l > 0 {
		n += 1 + l + sovSyncQuery(uint64(l))
	}
	l = len(m.ParquetParticlesUrl)
	if l > 0 {
		n += 1 + l + sovSyncQuery(uint64(l))
	}
	l = len(m.ParquetLinksUrl)
	if l > 0 {
		n += 1 + l + sovSyncQuery(uint64(l))
	}
	l = len(m.ParquetNeuronsUrl)
	if l > 0 {
		n += 1 + l + sovSyncQuery(uint64(l))
	}
	if m.ProtobufSize != 0 {
		n += 1 + sovSyncQuery(uint64(m.ProtobufSize))
	}
	if m.ParquetParticlesSize != 0 {
		n += 1 + sovSyncQuery(uint64(m.ParquetParticlesSize))
	}
	if m.ParquetLinksSize != 0 {
		n += 1 + sovSyncQuery(uint64(m.ParquetLinksSize))
	}
	if m.ParquetNeuronsSize != 0 {
		n += 1 + sovSyncQuery(uint64(m.ParquetNeuronsSize))
	}
	l = len(m.ProtobufChecksum)
	if l > 0 {
		n += 2 + l + sovSyncQuery(uint64(l))
	}
	return n
}

func (m *SubscribeGraphRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SinceHeight != 0 {
		n += 1 + sovSyncQuery(uint64(m.SinceHeight))
	}
	return n
}

func (m *GraphUpdate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.FromHeight != 0 {
		n += 1 + sovSyncQuery(uint64(m.FromHeight))
	}
	if m.ToHeight != 0 {
		n += 1 + sovSyncQuery(uint64(m.ToHeight))
	}
	if m.Timestamp != 0 {
		n += 1 + sovSyncQuery(uint64(m.Timestamp))
	}
	if len(m.NewParticles) > 0 {
		for _, e := range m.NewParticles {
			l = e.Size()
			n += 1 + l + sovSyncQuery(uint64(l))
		}
	}
	if len(m.NewLinks) > 0 {
		for _, e := range m.NewLinks {
			l = e.Size()
			n += 1 + l + sovSyncQuery(uint64(l))
		}
	}
	if len(m.NewNeurons) > 0 {
		for _, e := range m.NewNeurons {
			l = e.Size()
			n += 1 + l + sovSyncQuery(uint64(l))
		}
	}
	if len(m.RankUpdates) > 0 {
		for _, e := range m.RankUpdates {
			l = e.Size()
			n += 1 + l + sovSyncQuery(uint64(l))
		}
	}
	if m.TotalParticles != 0 {
		n += 1 + sovSyncQuery(uint64(m.TotalParticles))
	}
	if m.TotalLinks != 0 {
		n += 1 + sovSyncQuery(uint64(m.TotalLinks))
	}
	if m.TotalNeurons != 0 {
		n += 1 + sovSyncQuery(uint64(m.TotalNeurons))
	}
	return n
}

func (m *RankDelta) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Particle != 0 {
		n += 1 + sovSyncQuery(uint64(m.Particle))
	}
	if m.Rank != 0 {
		n += 1 + sovSyncQuery(uint64(m.Rank))
	}
	return n
}

func sovSyncQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSyncQuery(x uint64) (n int) {
	return sovSyncQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryLatestSnapshotRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSyncQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLatestSnapshotRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLatestSnapshotRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipSyncQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSyncQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLatestSnapshotResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSyncQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLatestSnapshotResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLatestSnapshotResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyncQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSyncQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSyncQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyncQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyncQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParticlesCount", wireType)
			}
			m.ParticlesCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyncQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ParticlesCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LinksCount", wireType)
			}
			m.LinksCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyncQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LinksCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NeuronsCount", wireType)
			}
			m.NeuronsCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyncQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NeuronsCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RankMerkleRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyncQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSyncQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSyncQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RankMerkleRoot = append(m.RankMerkleRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.RankMerkleRoot == nil {
				m.RankMerkleRoot = []byte{}
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProtobufUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyncQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSyncQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSyncQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProtobufUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParquetParticlesUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyncQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSyncQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSyncQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ParquetParticlesUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParquetLinksUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyncQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSyncQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSyncQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ParquetLinksUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParquetNeuronsUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyncQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSyncQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSyncQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ParquetNeuronsUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProtobufSize", wireType)
			}
			m.ProtobufSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyncQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProtobufSize |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParquetParticlesSize", wireType)
			}
			m.ParquetParticlesSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyncQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ParquetParticlesSize |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParquetLinksSize", wireType)
			}
			m.ParquetLinksSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyncQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ParquetLinksSize |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParquetNeuronsSize", wireType)
			}
			m.ParquetNeuronsSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyncQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ParquetNeuronsSize |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProtobufChecksum", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyncQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSyncQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSyncQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProtobufChecksum = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSyncQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSyncQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SubscribeGraphRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSyncQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SubscribeGraphRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SubscribeGraphRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SinceHeight", wireType)
			}
			m.SinceHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyncQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SinceHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSyncQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSyncQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GraphUpdate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSyncQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GraphUpdate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GraphUpdate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromHeight", wireType)
			}
			m.FromHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyncQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FromHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToHeight", wireType)
			}
			m.ToHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyncQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ToHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyncQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewParticles", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyncQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSyncQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSyncQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewParticles = append(m.NewParticles, &Particle{})
			if err := m.NewParticles[len(m.NewParticles)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewLinks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyncQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSyncQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSyncQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewLinks = append(m.NewLinks, &Cyberlink{})
			if err := m.NewLinks[len(m.NewLinks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewNeurons", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyncQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSyncQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSyncQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewNeurons = append(m.NewNeurons, &Neuron{})
			if err := m.NewNeurons[len(m.NewNeurons)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RankUpdates", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyncQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSyncQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSyncQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RankUpdates = append(m.RankUpdates, &RankDelta{})
			if err := m.RankUpdates[len(m.RankUpdates)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalParticles", wireType)
			}
			m.TotalParticles = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyncQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalParticles |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalLinks", wireType)
			}
			m.TotalLinks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyncQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalLinks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalNeurons", wireType)
			}
			m.TotalNeurons = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyncQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalNeurons |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSyncQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSyncQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RankDelta) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSyncQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RankDelta: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RankDelta: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Particle", wireType)
			}
			m.Particle = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyncQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Particle |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rank", wireType)
			}
			m.Rank = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyncQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Rank |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSyncQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSyncQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSyncQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSyncQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSyncQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSyncQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSyncQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSyncQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSyncQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSyncQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSyncQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSyncQuery = fmt.Errorf("proto: unexpected end of group")
)
