// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: cyber/graph/v1beta1/sync_query.proto

/*
Package types is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package types

import (
	"context"
	"io"
	"net/http"

	"github.com/golang/protobuf/descriptor"
	"github.com/golang/protobuf/proto"
	"github.com/grpc-ecosystem/grpc-gateway/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = descriptor.ForMessage
var _ = metadata.Join

func request_GraphSyncQuery_LatestSnapshot_0(ctx context.Context, marshaler runtime.Marshaler, client GraphSyncQueryClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq QueryLatestSnapshotRequest
	var metadata runtime.ServerMetadata

	msg, err := client.LatestSnapshot(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_GraphSyncQuery_LatestSnapshot_0(ctx context.Context, marshaler runtime.Marshaler, server GraphSyncQueryServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq QueryLatestSnapshotRequest
	var metadata runtime.ServerMetadata

	msg, err := server.LatestSnapshot(ctx, &protoReq)
	return msg, metadata, err

}

var (
	filter_GraphSyncQuery_SubscribeGraph_0 = &utilities.DoubleArray{Encoding: map[string]int{}, Base: []int(nil), Check: []int(nil)}
)

func request_GraphSyncQuery_SubscribeGraph_0(ctx context.Context, marshaler runtime.Marshaler, client GraphSyncQueryClient, req *http.Request, pathParams map[string]string) (GraphSyncQuery_SubscribeGraphClient, runtime.ServerMetadata, error) {
	var protoReq SubscribeGraphRequest
	var metadata runtime.ServerMetadata

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_GraphSyncQuery_SubscribeGraph_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	stream, err := client.SubscribeGraph(ctx, &protoReq)
	if err != nil {
		return nil, metadata, err
	}
	header, err := stream.Header()
	if err != nil {
		return nil, metadata, err
	}
	metadata.HeaderMD = header
	return stream, metadata, nil

}

// RegisterGraphSyncQueryHandlerServer registers the http handlers for service GraphSyncQuery to "mux".
// UnaryRPC     :call GraphSyncQueryServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterGraphSyncQueryHandlerFromEndpoint instead.
func RegisterGraphSyncQueryHandlerServer(ctx context.Context, mux *runtime.ServeMux, server GraphSyncQueryServer) error {

	mux.Handle("GET", pattern_GraphSyncQuery_LatestSnapshot_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateIncomingContext(ctx, mux, req)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_GraphSyncQuery_LatestSnapshot_0(rctx, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_GraphSyncQuery_LatestSnapshot_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("GET", pattern_GraphSyncQuery_SubscribeGraph_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		err := status.Error(codes.Unimplemented, "streaming calls are not yet supported in the in-process transport")
		_, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
		return
	})

	return nil
}

// RegisterGraphSyncQueryHandlerFromEndpoint is same as RegisterGraphSyncQueryHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterGraphSyncQueryHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.Dial(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterGraphSyncQueryHandler(ctx, mux, conn)
}

// RegisterGraphSyncQueryHandler registers the http handlers for service GraphSyncQuery to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterGraphSyncQueryHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterGraphSyncQueryHandlerClient(ctx, mux, NewGraphSyncQueryClient(conn))
}

// RegisterGraphSyncQueryHandlerClient registers the http handlers for service GraphSyncQuery
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "GraphSyncQueryClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "GraphSyncQueryClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "GraphSyncQueryClient" to call the correct interceptors.
func RegisterGraphSyncQueryHandlerClient(ctx context.Context, mux *runtime.ServeMux, client GraphSyncQueryClient) error {

	mux.Handle("GET", pattern_GraphSyncQuery_LatestSnapshot_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateContext(ctx, mux, req)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_GraphSyncQuery_LatestSnapshot_0(rctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_GraphSyncQuery_LatestSnapshot_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("GET", pattern_GraphSyncQuery_SubscribeGraph_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateContext(ctx, mux, req)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_GraphSyncQuery_SubscribeGraph_0(rctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_GraphSyncQuery_SubscribeGraph_0(ctx, mux, outboundMarshaler, w, req, func() (proto.Message, error) { return resp.Recv() }, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_GraphSyncQuery_LatestSnapshot_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3, 2, 4}, []string{"cyber", "graph", "v1beta1", "snapshot", "latest"}, "", runtime.AssumeColonVerbOpt(false)))

	pattern_GraphSyncQuery_SubscribeGraph_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3, 2, 4}, []string{"cyber", "graph", "v1beta1", "snapshot", "subscribe"}, "", runtime.AssumeColonVerbOpt(false)))
)

var (
	forward_GraphSyncQuery_LatestSnapshot_0 = runtime.ForwardResponseMessage

	forward_GraphSyncQuery_SubscribeGraph_0 = runtime.ForwardResponseStream
)
